name: Matrix

on: push

jobs:
    node-version:
        strategy:
            fail-fast: true
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                node-version: [6, 8, 10]
                exclude:
                    - os: macos-latest
                      node-version: 8
                    - os: windows-latest
                      node-version: 6
                include:
                    - os: ubuntu-latest
                      node-version: 4
                    - os: ubuntu-latest
                      node-version: 8
                      is_ubuntu_8: "true"
        runs-on: ${{ matrix.os }}
        env:
            is_ubuntu_8: ${{ matrix.is_ubuntu_8 }}
        steps:
            - name: Log node version
              run: node -v
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Log node version
              run: |
                  node -v
                  echo $is_ubuntu_8
